// <auto-generated />
using System;
using CompositionMaster;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CompositionMaster.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260324175726_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CompositionMaster.Models.Nomenclature", b =>
                {
                    b.Property<int>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("identifier");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Identifier"));

                    b.Property<string>("DSECode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dsecode");

                    b.Property<DateTime>("IntroducedIntoUse")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("introducedintouse");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("NomenclatureType")
                        .HasColumnType("integer")
                        .HasColumnName("nomenclaturetype");

                    b.Property<string>("SubsystemCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subsystemcode");

                    b.Property<int>("UnitOfMeasurement")
                        .HasColumnType("integer")
                        .HasColumnName("unitofmeasurement");

                    b.HasKey("Identifier");

                    b.ToTable("nomenclature", (string)null);
                });

            modelBuilder.Entity("CompositionMaster.Models.NomenclatureChange", b =>
                {
                    b.Property<int>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("identifier");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Identifier"));

                    b.Property<int>("Author")
                        .HasColumnType("integer")
                        .HasColumnName("author");

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changedate");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<string>("DSECode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dsecode");

                    b.Property<DateTime>("IntroducedIntoUse")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("introducedintouse");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("SubsystemCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subsystemcode");

                    b.HasKey("Identifier");

                    b.ToTable("nomenclature_change", (string)null);
                });

            modelBuilder.Entity("CompositionMaster.Models.NomenclatureType", b =>
                {
                    b.Property<int>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("identifier");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Identifier"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Identifier");

                    b.ToTable("nomenclature_type", (string)null);
                });

            modelBuilder.Entity("CompositionMaster.Models.OperationCard", b =>
                {
                    b.Property<int>("Identifier")
                        .HasColumnType("integer")
                        .HasColumnName("identifier");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer")
                        .HasColumnName("linenumber");

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric")
                        .HasColumnName("cost");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<string>("Equipment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("equipment");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("operation");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("section");

                    b.Property<decimal>("Sum")
                        .HasColumnType("numeric")
                        .HasColumnName("sum");

                    b.Property<decimal>("Tariff")
                        .HasColumnType("numeric")
                        .HasColumnName("tariff");

                    b.Property<decimal>("TimeNorm")
                        .HasColumnType("numeric")
                        .HasColumnName("timenorm");

                    b.HasKey("Identifier", "LineNumber");

                    b.ToTable("operation_card", (string)null);
                });

            modelBuilder.Entity("CompositionMaster.Models.OperationCardChange", b =>
                {
                    b.Property<int>("Identifier")
                        .HasColumnType("integer")
                        .HasColumnName("identifier");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer")
                        .HasColumnName("linenumber");

                    b.Property<int>("Author")
                        .HasColumnType("integer")
                        .HasColumnName("author");

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric")
                        .HasColumnName("cost");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<string>("Equipment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("equipment");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("operation");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("section");

                    b.Property<decimal>("Sum")
                        .HasColumnType("numeric")
                        .HasColumnName("sum");

                    b.Property<decimal>("Tariff")
                        .HasColumnType("numeric")
                        .HasColumnName("tariff");

                    b.Property<decimal>("TimeNorm")
                        .HasColumnType("numeric")
                        .HasColumnName("timenorm");

                    b.HasKey("Identifier", "LineNumber");

                    b.ToTable("operation_card_change", (string)null);
                });

            modelBuilder.Entity("CompositionMaster.Models.Position", b =>
                {
                    b.Property<int>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("identifier");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Identifier"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Identifier");

                    b.ToTable("position", (string)null);
                });

            modelBuilder.Entity("CompositionMaster.Models.Role", b =>
                {
                    b.Property<int>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("identifier");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Identifier"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Identifier");

                    b.ToTable("role", (string)null);
                });

            modelBuilder.Entity("CompositionMaster.Models.Specification", b =>
                {
                    b.Property<int>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("identifier");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Identifier"));

                    b.Property<DateTime>("InputDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inputdate");

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean")
                        .HasColumnName("ismain");

                    b.Property<DateTime>("OutputDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("outputdate");

                    b.Property<int>("Owner")
                        .HasColumnType("integer")
                        .HasColumnName("owner");

                    b.HasKey("Identifier");

                    b.ToTable("specification", (string)null);
                });

            modelBuilder.Entity("CompositionMaster.Models.SpecificationChange", b =>
                {
                    b.Property<int>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("identifier");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Identifier"));

                    b.Property<int>("Author")
                        .HasColumnType("integer")
                        .HasColumnName("author");

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changedate");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("InputDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inputdate");

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean")
                        .HasColumnName("ismain");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("OutputDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("outputdate");

                    b.Property<int>("Owner")
                        .HasColumnType("integer")
                        .HasColumnName("owner");

                    b.HasKey("Identifier");

                    b.ToTable("specification_change", (string)null);
                });

            modelBuilder.Entity("CompositionMaster.Models.SpecificationComponent", b =>
                {
                    b.Property<int>("Identifier")
                        .HasColumnType("integer")
                        .HasColumnName("identifier");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer")
                        .HasColumnName("linenumber");

                    b.Property<int>("Nomenclature")
                        .HasColumnType("integer")
                        .HasColumnName("nomenclature");

                    b.Property<bool>("ParticipatesInCalculation")
                        .HasColumnType("boolean")
                        .HasColumnName("participatesincalculation");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.HasKey("Identifier", "LineNumber");

                    b.ToTable("specification_component", (string)null);
                });

            modelBuilder.Entity("CompositionMaster.Models.SpecificationComponentChange", b =>
                {
                    b.Property<int>("Identifier")
                        .HasColumnType("integer")
                        .HasColumnName("identifier");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer")
                        .HasColumnName("linenumber");

                    b.Property<int>("Author")
                        .HasColumnType("integer")
                        .HasColumnName("author");

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changedate");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<int>("Nomenclature")
                        .HasColumnType("integer")
                        .HasColumnName("nomenclature");

                    b.Property<bool>("ParticipatesInCalculation")
                        .HasColumnType("boolean")
                        .HasColumnName("participatesincalculation");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.HasKey("Identifier", "LineNumber");

                    b.ToTable("specification_component_change", (string)null);
                });

            modelBuilder.Entity("CompositionMaster.Models.UnitOfMeasurement", b =>
                {
                    b.Property<int>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("identifier");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Identifier"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("abbreviation");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Identifier");

                    b.ToTable("unit_of_measurement", (string)null);
                });

            modelBuilder.Entity("CompositionMaster.Models.User", b =>
                {
                    b.Property<int>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("identifier");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Identifier"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fullname");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("login");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("roleid");

                    b.HasKey("Identifier");

                    b.HasIndex("RoleId");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("CompositionMaster.Models.User", b =>
                {
                    b.HasOne("CompositionMaster.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
